name: 自动更新博客索引

on:
  push:
    branches: [ main ]
    paths:
      - 'Blog/**/*.md'
      - '.github/scripts/generate_blog_index.py'
  workflow_dispatch:  # 新增：允许手动触发工作流

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 配置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 检查根目录结构
        run: |
          echo "当前工作目录：$(pwd)"
          echo "根目录文件列表："
          ls -la  # 查看根目录下是否有Blog文件夹
          echo "Blog目录内容："
          ls -la Blog  # 查看Blog目录下的md文件

      - name: 运行索引生成脚本
        run: python .github/scripts/generate_blog_index.py

      - name: 自动提交更新
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "自动更新博客索引 index.json"
          file_pattern: "Blog/index.json"
