name: 自动更新博客索引

on:
  push:
    branches: [ main ]
    paths:
      - 'Blog/**/*.md'  # 当Blog目录下的md文件变更时触发
      - '.github/scripts/generate_blog_index.py'  # 脚本本身变更时也触发

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 配置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 运行索引生成脚本
        run: python .github/scripts/generate_blog_index.py

      - name: 自动提交更新
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "自动更新博客索引 index.json"
          file_pattern: "Blog/index.json"  # 只提交index.json的变更
